### ISSUE TITLE
Conflict with "PHP Tools for VS Code"

### ISSUE THREAD

**Issue by soderlind** [johnbillion/vscode-wordpress-hooks#10]
<img width="534" alt="composer json — read-offline 2020-07-15 23-17-49" src="https://user-images.githubusercontent.com/1649452/87597163-9d7f3900-c6f1-11ea-99ef-666f885e9e7f.png">

macos: 10.15.5 (19F101)
vs code: 1.47.1
[php tools](https://www.devsense.com/en): 1.0.4908
vscode-wordpress-hooks: 0.2.1

**Comment by johnbillion** [comment]
This seems like something to report to PHP Tools as this message comes from that extension. Let me know if that's not the case.

**Comment by soderlind** [comment]
Ok, reported at https://github.com/DEVSENSE/phptools-docs/issues/60
