### ISSUE TITLE
Make this extension available on Open VSX

### ISSUE THREAD

**Issue by davelavoie** [johnbillion/vscode-wordpress-hooks#32]
Is it possible to add this extension to the [Open VSX repository](https://open-vsx.org/) ? This way, it could be installed and updated automatically for users using VS Code in environments such as GitPod.

The publishing process is available here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

The GitPod team explains why they use Open VSX here: https://www.gitpod.io/blog/open-vsx

Thanks :-)

**Comment by johnbillion** [comment]
Done: https://open-vsx.org/extension/johnbillion/vscode-wordpress-hooks.

Todo:

* [ ] Get the namespace granted: https://github.com/EclipseFdn/open-vsx.org/issues/763
* [ ] Perform subsequent deployments to Open VSX with the existing GitHub Action workflow that's in place for VSC Marketplace

**Comment by davelavoie** [comment]
Wow! That was fast! :-)

Thank you John!
