### ISSUE TITLE
Feature request: Add type hints

### ISSUE THREAD

**Issue by soderlind** [johnbillion/vscode-wordpress-hooks#5]
When adding an autocompleted closure callback, please add type hints (could be toggled on/off in settings), eg:

```php
add_filter( 'template_directory', function( string $template_dir, string $template, string $theme_root ) {
    |
}, 10, 3 );
```

If the type hint is an object, it should be escaped, as in:

```php
add_action( 'pre_get_posts', function( \WP_Query $this ) {
	
}  );
```

**Comment by johnbillion** [comment]
Whoops I missed this. Good idea, I've been wanting this too.

Notes:

* Any parameter which accepts multiple types should not be type hinted
* Needs to be a setting to enable/disable

**Comment by soderlind** [comment]
:)
